# Generated by Django 5.1.7 on 2025-04-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_varient_slug_pv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug_product",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
