# Generated by Django 5.1.7 on 2025-03-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("phone_no", models.CharField(max_length=15, unique=True)),
                ("last_login_at", models.DateTimeField(auto_now=True)),
                ("email_verified_at", models.DateField(auto_now_add=True)),
                ("type", models.CharField(max_length=25)),
                ("profile_image", models.ImageField(upload_to="images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
