# Generated by Django 5.1.7 on 2025-03-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_address"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user_details",
        ),
    ]
