# Generated by Django 5.1.7 on 2025-03-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_table"),
        ("order_section", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="User_data",
        ),
    ]
