# Generated by Django 5.1.7 on 2025-03-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_user_user_data"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user_data",
            table=None,
        ),
    ]
